export interface SemiThemeOptions {
    name?: string
}

export interface SemiVitePluginOptions {
    /**
     * Custom theme. Pass the npm package name generated by Semi DSM,
     * or an object with `{ name }`.
     */
    theme?: string | SemiThemeOptions;
    /**
     * Wrap final CSS with `@layer semi { ... }`.
     */
    cssLayer?: boolean;
    /**
     * Prefix of the CSS selector. Default is `semi`.
     */
    prefixCls?: string;
    /**
     * Key-value pair of Scss variables. e.g. `{ '$font-size-small': '16px' }`
     */
    variables?: Record<string, string | number>;
    /**
     * Absolute path of a local Scss file that will be injected after theme variables.
     */
    include?: string;
    /**
     * Omit the `import xxx.css` statements emitted from semi packages.
     * Useful for Next.js/SSR scenarios where global css cannot be imported from node_modules.
     */
    omitCss?: boolean
}
