const dependentTree = {
    "Anchor": ["Typography"],
    "AudioPlayer": ["Button", "Dropdown", "Image", "Tooltip", "Popover", "Icon"],
    "AutoComplete": ["Spin", "Popover", "Input", "Icon"],
    "Avatar": [] as any,
    "AvatarGroup": [] as any,
    "BackTop": ["Icon"],
    "Badge": [] as any,
    "Banner": ["IconButton", "Typography", "Icon"],
    "Breadcrumb": ["Popover", "Typography", "Icon"],
    "Button": ["Icon"],
    "ButtonGroup": ["Button"],
    "SplitButtonGroup": ["Button"],
    "Calendar": ["Popover", "Button", "Icon"],
    "Card": ["Space", "Skeleton", "Typography"],
    "Carousel": ["Icon"],
    "Cascader": ["Input", "Popover", "Tag", "TagInput", "Spin", "Checkbox", "Icon"],
    "Chat": ["TextArea", "Button", "Upload", "Toast", "Progress", "Image", "Avatar", "Icon", "MarkdownRender", "Typography", "Tooltip", "Divider", "Popconfirm", "BackTop"],
    "Checkbox": ["Icon"],
    "CodeHighlight": [] as any,
    "CheckboxGroup": ["Icon"],
    "Collapse": ["Collapsible", "Icon"],
    "Collapsible": [] as any,
    "ColorPicker": ["Popover", "Input", "InputGroup", "InputNumber", "Select", "Button"],
    "Cropper": [] as any,
    "DatePicker": ["Button", "Input", "IconButton", "Icon", "Typography", "ScrollList", "Icon"],
    "Descriptions": [] as any,
    "Divider": [] as any,
    "Dropdown": ["Tooltip", "Icon"],
    "Empty": ["Typography"],
    "Form": ["Row", "Col", "Icon"],
    "Row": [] as any,
    "Col": [] as any,
    "Highlight": [] as any,
    "HotKeys": [] as any,
    "IconButton": ["Button", "Spin", "Icon"],
    "Image": ["Skeleton", "Divider", "Tooltip", "Slider", "Spin", "Portal", "Icon"],
    "Input": ["Icon"],
    "InputGroup": ["Form"],
    "TextArea": ["Icon"],
    "InputNumber": ["Input", "Icon"],
    "JsonViewer": ["Button", "Input", "Icon"],
    "Layout": [] as any,
    "List": ["Row", "Spin"],
    "MarkdownRender": ["Typography", "CodeHighlight", "Image", "Table", "Icon"],
    "Modal": ["Button", "Portal", "Typography", "Icon"],
    "Navigation": ["Button", "Tooltip", "Dropdown", "Collapsible", "Icon"],
    "Notification": ["Button", "Icon"],
    "OverflowList": [] as any,
    "Pagination": ["Select", "InputNumber", "Popover", "Icon"],
    "PinCode": ["Input"],
    "Popconfirm": ["Popover", "Button", "Icon"],
    "Popover": ["Tooltip"],
    "Portal": [] as any,
    "Progress": [] as any,
    "Radio": ["Icon"],
    "Rating": ["Icon", "Tooltip"],
    "Resizable": ["Icon"],
    "ScrollList": [] as any,
    "Select": ["Tag", "OverflowList", "Space", "Typography", "Spin", "Popover", "Icon"],
    "SideSheet": ["[Portal", "Button", "Icon"],
    "Skeleton": [] as any,
    "Slider": ["Tooltip"],
    "Space": [] as any,
    "Spin": [] as any,
    "Steps": ["Row", "Col", "Icon"],
    "Switch": ["Spin"],
    "Table": ["Radio", "Checkbox", "Dropdown", "Spin", "Pagination", "Icon"],
    "Tabs": ["OverflowList", "Dropdown", "Button", "Icon"],
    "Tag": ["Icon", "Popover", "Avatar"],
    "TagGroup": ["Icon", "Popover", "Avatar"],
    "TagInput": ["Tag", "Input", "Popover", "Icon"],
    "Timeline": [] as any,
    "TimePicker": ["Input", "Icon", "Popover", "ScrollList"],
    "Toast": ["Button", "Icon"],
    "Tooltip": ["Portal"],
    "Transfer": ["Input", "Checkbox", "Tree", "Button", "Spin", "Icon"],
    "Tree": ["Input", "Checkbox", "Spin", "Collapsible", "Icon"],
    "TreeSelect": ["Tag", "TagInput", "Checkbox", "Popover", "Input", "Icon"],
    "Typography": ["Popover", "Tooltip", "Icon"],
    "Upload": ["Button", "Progress", "Tooltip", "Spin", "Icon"],
    "UserGuide": ["Popover", "Button", "Modal"]
};
  
export default dependentTree;